//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnalysisResult) DeepCopyInto(out *AnalysisResult) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	out.AnalysisWindow = in.AnalysisWindow
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerRecommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnalysisResult.
func (in *AnalysisResult) DeepCopy() *AnalysisResult {
	if in == nil {
		return nil
	}
	out := new(AnalysisResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArgoCDConfig) DeepCopyInto(out *ArgoCDConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArgoCDConfig.
func (in *ArgoCDConfig) DeepCopy() *ArgoCDConfig {
	if in == nil {
		return nil
	}
	out := new(ArgoCDConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Atelier) DeepCopyInto(out *Atelier) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Atelier.
func (in *Atelier) DeepCopy() *Atelier {
	if in == nil {
		return nil
	}
	out := new(Atelier)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Atelier) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtelierList) DeepCopyInto(out *AtelierList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Atelier, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtelierList.
func (in *AtelierList) DeepCopy() *AtelierList {
	if in == nil {
		return nil
	}
	out := new(AtelierList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AtelierList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtelierSpec) DeepCopyInto(out *AtelierSpec) {
	*out = *in
	in.Prometheus.DeepCopyInto(&out.Prometheus)
	out.GitProvider = in.GitProvider
	if in.SafetyRails != nil {
		in, out := &in.SafetyRails, &out.SafetyRails
		*out = new(SafetyRailsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PRSettings != nil {
		in, out := &in.PRSettings, &out.PRSettings
		*out = new(PRSettingsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ArgoCD != nil {
		in, out := &in.ArgoCD, &out.ArgoCD
		*out = new(ArgoCDConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.OpenCost != nil {
		in, out := &in.OpenCost, &out.OpenCost
		*out = new(OpenCostConfig)
		**out = **in
	}
	if in.DefaultAnalysisWindow != nil {
		in, out := &in.DefaultAnalysisWindow, &out.DefaultAnalysisWindow
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtelierSpec.
func (in *AtelierSpec) DeepCopy() *AtelierSpec {
	if in == nil {
		return nil
	}
	out := new(AtelierSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AtelierStatus) DeepCopyInto(out *AtelierStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastPrometheusCheck != nil {
		in, out := &in.LastPrometheusCheck, &out.LastPrometheusCheck
		*out = (*in).DeepCopy()
	}
	if in.LastGitProviderCheck != nil {
		in, out := &in.LastGitProviderCheck, &out.LastGitProviderCheck
		*out = (*in).DeepCopy()
	}
	if in.LastArgoCDCheck != nil {
		in, out := &in.LastArgoCDCheck, &out.LastArgoCDCheck
		*out = (*in).DeepCopy()
	}
	if in.LastOpenCostCheck != nil {
		in, out := &in.LastOpenCostCheck, &out.LastOpenCostCheck
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AtelierStatus.
func (in *AtelierStatus) DeepCopy() *AtelierStatus {
	if in == nil {
		return nil
	}
	out := new(AtelierStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRecommendation) DeepCopyInto(out *ContainerRecommendation) {
	*out = *in
	in.Current.DeepCopyInto(&out.Current)
	in.Recommended.DeepCopyInto(&out.Recommended)
	if in.P95CPU != nil {
		in, out := &in.P95CPU, &out.P95CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.P99CPU != nil {
		in, out := &in.P99CPU, &out.P99CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.P95Memory != nil {
		in, out := &in.P95Memory, &out.P95Memory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.P99Memory != nil {
		in, out := &in.P99Memory, &out.P99Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRecommendation.
func (in *ContainerRecommendation) DeepCopy() *ContainerRecommendation {
	if in == nil {
		return nil
	}
	out := new(ContainerRecommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FitProfile) DeepCopyInto(out *FitProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FitProfile.
func (in *FitProfile) DeepCopy() *FitProfile {
	if in == nil {
		return nil
	}
	out := new(FitProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FitProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FitProfileList) DeepCopyInto(out *FitProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FitProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FitProfileList.
func (in *FitProfileList) DeepCopy() *FitProfileList {
	if in == nil {
		return nil
	}
	out := new(FitProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FitProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FitProfileRef) DeepCopyInto(out *FitProfileRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FitProfileRef.
func (in *FitProfileRef) DeepCopy() *FitProfileRef {
	if in == nil {
		return nil
	}
	out := new(FitProfileRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FitProfileSpec) DeepCopyInto(out *FitProfileSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = new(runtime.RawExtension)
		(*in).DeepCopyInto(*out)
	}
	if in.SafetyRailsOverride != nil {
		in, out := &in.SafetyRailsOverride, &out.SafetyRailsOverride
		*out = new(SafetyRailsConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FitProfileSpec.
func (in *FitProfileSpec) DeepCopy() *FitProfileSpec {
	if in == nil {
		return nil
	}
	out := new(FitProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FitProfileStatus) DeepCopyInto(out *FitProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastValidated != nil {
		in, out := &in.LastValidated, &out.LastValidated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FitProfileStatus.
func (in *FitProfileStatus) DeepCopy() *FitProfileStatus {
	if in == nil {
		return nil
	}
	out := new(FitProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitProviderConfig) DeepCopyInto(out *GitProviderConfig) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitProviderConfig.
func (in *GitProviderConfig) DeepCopy() *GitProviderConfig {
	if in == nil {
		return nil
	}
	out := new(GitProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenCostConfig) DeepCopyInto(out *OpenCostConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenCostConfig.
func (in *OpenCostConfig) DeepCopy() *OpenCostConfig {
	if in == nil {
		return nil
	}
	out := new(OpenCostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PRSettingsConfig) DeepCopyInto(out *PRSettingsConfig) {
	*out = *in
	if in.CooldownPeriod != nil {
		in, out := &in.CooldownPeriod, &out.CooldownPeriod
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MinChangePercent != nil {
		in, out := &in.MinChangePercent, &out.MinChangePercent
		*out = new(int32)
		**out = **in
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PRSettingsConfig.
func (in *PRSettingsConfig) DeepCopy() *PRSettingsConfig {
	if in == nil {
		return nil
	}
	out := new(PRSettingsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrometheusConfig) DeepCopyInto(out *PrometheusConfig) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrometheusConfig.
func (in *PrometheusConfig) DeepCopy() *PrometheusConfig {
	if in == nil {
		return nil
	}
	out := new(PrometheusConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceRequirements) DeepCopyInto(out *ResourceRequirements) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = new(ResourceValues)
		(*in).DeepCopyInto(*out)
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = new(ResourceValues)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceRequirements.
func (in *ResourceRequirements) DeepCopy() *ResourceRequirements {
	if in == nil {
		return nil
	}
	out := new(ResourceRequirements)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceValues) DeepCopyInto(out *ResourceValues) {
	*out = *in
	if in.CPU != nil {
		in, out := &in.CPU, &out.CPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Memory != nil {
		in, out := &in.Memory, &out.Memory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceValues.
func (in *ResourceValues) DeepCopy() *ResourceValues {
	if in == nil {
		return nil
	}
	out := new(ResourceValues)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SafetyRailsConfig) DeepCopyInto(out *SafetyRailsConfig) {
	*out = *in
	if in.MinCPU != nil {
		in, out := &in.MinCPU, &out.MinCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinMemory != nil {
		in, out := &in.MinMemory, &out.MinMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxCPU != nil {
		in, out := &in.MaxCPU, &out.MaxCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxMemory != nil {
		in, out := &in.MaxMemory, &out.MaxMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SafetyRailsConfig.
func (in *SafetyRailsConfig) DeepCopy() *SafetyRailsConfig {
	if in == nil {
		return nil
	}
	out := new(SafetyRailsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tailoring) DeepCopyInto(out *Tailoring) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tailoring.
func (in *Tailoring) DeepCopy() *Tailoring {
	if in == nil {
		return nil
	}
	out := new(Tailoring)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Tailoring) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailoringList) DeepCopyInto(out *TailoringList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Tailoring, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailoringList.
func (in *TailoringList) DeepCopy() *TailoringList {
	if in == nil {
		return nil
	}
	out := new(TailoringList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TailoringList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailoringSpec) DeepCopyInto(out *TailoringSpec) {
	*out = *in
	out.Target = in.Target
	out.FitProfileRef = in.FitProfileRef
	out.WriteBack = in.WriteBack
	if in.AnalysisWindow != nil {
		in, out := &in.AnalysisWindow, &out.AnalysisWindow
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.ExcludeContainers != nil {
		in, out := &in.ExcludeContainers, &out.ExcludeContainers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailoringSpec.
func (in *TailoringSpec) DeepCopy() *TailoringSpec {
	if in == nil {
		return nil
	}
	out := new(TailoringSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TailoringStatus) DeepCopyInto(out *TailoringStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAnalysis != nil {
		in, out := &in.LastAnalysis, &out.LastAnalysis
		*out = new(AnalysisResult)
		(*in).DeepCopyInto(*out)
	}
	if in.NextAnalysisTime != nil {
		in, out := &in.NextAnalysisTime, &out.NextAnalysisTime
		*out = (*in).DeepCopy()
	}
	if in.MergedAt != nil {
		in, out := &in.MergedAt, &out.MergedAt
		*out = (*in).DeepCopy()
	}
	if in.ArgoCDSyncTime != nil {
		in, out := &in.ArgoCDSyncTime, &out.ArgoCDSyncTime
		*out = (*in).DeepCopy()
	}
	if in.LastPRUpdateTime != nil {
		in, out := &in.LastPRUpdateTime, &out.LastPRUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TailoringStatus.
func (in *TailoringStatus) DeepCopy() *TailoringStatus {
	if in == nil {
		return nil
	}
	out := new(TailoringStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRef) DeepCopyInto(out *TargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRef.
func (in *TargetRef) DeepCopy() *TargetRef {
	if in == nil {
		return nil
	}
	out := new(TargetRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WriteBackConfig) DeepCopyInto(out *WriteBackConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WriteBackConfig.
func (in *WriteBackConfig) DeepCopy() *WriteBackConfig {
	if in == nil {
		return nil
	}
	out := new(WriteBackConfig)
	in.DeepCopyInto(out)
	return out
}
